name: SMS Service Playwright Tests
on:
  pull_request:
    types: closed
    branches: main
  workflow_dispatch:

jobs:
  test:
    environment: test
    env: 
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      PAT_PASSWORD: ${{ secrets.PAT_PASSWORD }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: dependecy-modules-${{ hashFiles('**/pakage-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run sms-service-test
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
